# Generated by Django 6.0.4 on 2026-05-21 10:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rola', models.CharField(choices=[('GOSC', 'Niezalogowany Gość'), ('KLUBOWICZ', 'Klubowicz'), ('TRENER', 'Trener Personalny'), ('RECEPCJA', 'Pracownik Recepcji'), ('ADMIN', 'Administrator')], default='GOSC', max_length=20)),
                ('zdjecie_identyfikacyjne', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Karnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('typ', models.CharField(choices=[('OPEN', 'Karnet Open'), ('STUDENT', 'Karnet Studencki'), ('RELAX', 'Karnet Weekendowy')], default='OPEN', max_length=30)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karnety', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTreningowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_treningu', models.TextField()),
                ('data_utworzenia', models.DateField(auto_now_add=True)),
                ('podopieczny', models.ForeignKey(limit_choices_to={'rola': 'KLUBOWICZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='plany_treningowe', to=settings.AUTH_USER_MODEL)),
                ('trener', models.ForeignKey(limit_choices_to={'rola': 'TRENER'}, on_delete=django.db.models.deletion.CASCADE, related_name='utworzone_plany', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zajecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('data_czas', models.DateTimeField()),
                ('limit_miejsc', models.IntegerField()),
                ('trener', models.ForeignKey(limit_choices_to={'rola': 'TRENER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prowadzone_zajecia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zapisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(limit_choices_to={'rola': 'KLUBOWICZ'}, on_delete=django.db.models.deletion.CASCADE, related_name='moje_zapisy', to=settings.AUTH_USER_MODEL)),
                ('zajecia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisani_uzytkownicy', to='gym_management.zajecia')),
            ],
            options={
                'unique_together': {('uzytkownik', 'zajecia')},
            },
        ),
    ]
